# web or data mining 
- dputils

In [ ]:
from dputils.scrape import Scraper, Tag

In [ ]:
url = "https://pypi.org/"

sc = Scraper(url)

content = sc.get_tag(Tag("body"))

In [ ]:
print(content.get('body'))

Flipkart example

In [5]:
url ='https://www.flipkart.com/cameras/dslr-mirrorless/pr?sid=jek%2Cp31%2Ctrv'
flipkart = Scraper(url)

Selecting a random User-Agent...
Randomly picked browser: Safari
Randomly picked operating system: Mac
🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐
User agent:  {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15'}
Cookies:  {'session-id': '', 'session-id-time': '', 'session-token': ''}
url:  https://www.flipkart.com/cameras/dslr-mirrorless/pr?sid=jek%2Cp31%2Ctrv
🌐🌐🌐🌐🌐🌐🌐🌐🌐🌐

In [6]:
t = Tag(cls='_1YokD2 _3Mn1Gg') # target 
items = Tag(cls='_2kHMtA') # Repeating items
# tag data to be extract
n = Tag(cls='_4rR01T')
p = Tag(cls='_30jeq3 _1_WHN1')
ar = Tag(cls='_3LWZlK')
rc = Tag('span', cls='_2_R_DZ')

out = flipkart.get_repeating_page_data(
    target= t,
    items= items,
    name = p,
    avg_rating = ar,
    rating_count = rc 

)

In [7]:
import pandas as pd 
pd.DataFrame(out)

         name avg_rating                    rating_count
0     ₹47,990        4.4        202 Ratings & 19 Reviews
1     ₹61,489        4.5        868 Ratings & 94 Reviews
2     ₹77,990        4.5       709 Ratings & 109 Reviews
3     ₹41,990        4.5  16,382 Ratings & 2,180 Reviews
4     ₹33,990        4.4  28,440 Ratings & 4,095 Reviews
5     ₹57,990        4.5     4,887 Ratings & 685 Reviews
6     ₹70,989        4.6        728 Ratings & 93 Reviews
7     ₹79,990        4.7         99 Ratings & 12 Reviews
8     ₹79,989        4.6        728 Ratings & 93 Reviews
9     ₹56,989        4.5        598 Ratings & 93 Reviews
10    ₹71,990        4.6        197 Ratings & 27 Reviews
11  ₹2,14,489          5           3 Ratings & 1 Reviews
12    ₹78,989        4.5        598 Ratings & 93 Reviews
13    ₹66,989        4.5        598 Ratings & 93 Reviews
14    ₹61,489        4.5        868 Ratings & 94 Reviews
15  ₹1,41,489        4.5        423 Ratings & 55 Reviews
16    ₹52,489        4.5        868 Ratings & 94 Reviews
17  ₹1,27,489        4.5        423 Ratings & 55 Reviews
18    ₹52,489        4.5        868 Ratings & 94 Reviews
19    ₹87,990        4.5        355 Ratings & 46 Reviews
20  ₹2,18,489        4.2         62 Ratings & 12 Reviews
21  ₹1,25,989        4.6         80 Ratings & 11 Reviews
22    ₹86,990        4.4     1,456 Ratings & 173 Reviews
23    ₹49,990        4.3         65 Ratings & 13 Reviews